package com.arvind.soap.webservices.soapcoursemanagement.soap;

import org.springframework.ws.server.endpoint.annotation.PayloadRoot;
import org.springframework.ws.server.endpoint.annotation.RequestPayload;
import org.springframework.ws.server.endpoint.annotation.ResponsePayload;

import com.arvind.soap.webservices.soapcourse.CourseDetails;
import com.arvind.soap.webservices.soapcourse.GetCourseDetailsRequest;
import com.arvind.soap.webservices.soapcourse.GetCourseDetailsResponse;
/*IMPORTANT use @Endpoint for spring boot to recognize this file as an endpoint*/

public class CoursDetailsEndpoint {
	/*
	 * The end point handles a request, processes it and generates a response for
	 * the request. the input is CourseDetailsRequest java class generated by jaxb
	 * the output is CourseDetailsResponse java class generated by jaxb from the xml
	 * schema. jaxb generates java objects from a given schema and xml files.
	 * 
	 * 
	 * 
	 * IMPORTANT: to prevent the wrong namespace and handle request getting
	 * processed by this endpoint and ensuring that the correct namespace and
	 * request is processed, you must define a PayLoadRoot with the required nms and
	 * request
	 */
	@PayloadRoot(namespace = "http://arvind.com/courses", localPart = "GetCourseDetailsRequest")
	@ResponsePayload
	public GetCourseDetailsResponse processCourseDetailsRequest(@RequestPayload GetCourseDetailsRequest request) {
		GetCourseDetailsResponse response = new GetCourseDetailsResponse();
		CourseDetails courseDetails = new CourseDetails();
		courseDetails.setId(request.getId());
		courseDetails.setName("Introduction to SpringBoot Edition 5");
		courseDetails.setDesc("A course that comprehensively covers the basic functions of SpringBoot ");

		response.setCourseDetails(courseDetails);

		return response;

	}

}
